import { readdirSync, statSync, writeFileSync } from 'node:fs'
import { join, relative, extname } from 'node:path'

// Convention:
// - Place client-island components under src/islands/*.client.tsx
// - Each file must export a component (named export) AND an `ISLAND_NAME` string.
//   Example:
//     export const ISLAND_NAME = 'Counter'
//     export function Counter(props: { initial: number }) { ... }
//
// This script generates src/client/islands.gen.ts which exports `islands` registry.

const ROOT = process.cwd()
const ISLANDS_DIR = join(ROOT, 'src', 'islands')
const OUT = join(ROOT, 'src', 'client', 'islands.gen.ts')

type Entry = { file: string; importPath: string }

function walk(dir: string, out: Entry[]) {
  if (!statSync(dir).isDirectory()) return
  for (const name of readdirSync(dir)) {
    const full = join(dir, name)
    const st = statSync(full)
    if (st.isDirectory()) walk(full, out)
    else if (st.isFile() && name.endsWith('.client.tsx')) {
      const rel = relative(join(ROOT, 'src', 'client'), full)
      // path from src/client -> src/islands/...
      const importPath = './' + rel.replace(/\\/g, '/').replace(/\.tsx$/, '')
      out.push({ file: full, importPath })
    }
  }
}

const entries: Entry[] = []
try {
  walk(ISLANDS_DIR, entries)
} catch {
  // no islands dir
}

const imports: string[] = []
const regs: string[] = []

entries.forEach((e, i) => {
  const alias = `m${i}`
  imports.push(`import * as ${alias} from ${JSON.stringify(e.importPath)}`)
  regs.push(`  [${alias}.ISLAND_NAME]: ${alias}[${alias}.ISLAND_NAME] ?? ${alias}.default ?? Object.values(${alias}).find((v) => typeof v === 'function')`)
})

const content = `// AUTO-GENERATED by scripts/gen-islands.ts
// Do not edit manually.

import type { IslandRegistry } from './islands'
${imports.join('\n')}

export const islands: IslandRegistry = {
${regs.join(',\n')}
}
`

writeFileSync(OUT, content)
console.log('[gen-islands] wrote', OUT)
