import { readdirSync, statSync, writeFileSync, existsSync } from 'node:fs'
import { join, relative, sep, posix } from 'node:path'

const ROOT = process.cwd()
const PAGES_DIR = join(ROOT, 'src', 'pages')
const OUT_FILE = join(ROOT, 'src', 'routes.fs.gen.ts')

function toPosix(p) {
  return p.split(sep).join(posix.sep)
}

function walk(dir, out) {
  if (!existsSync(dir)) return
  for (const name of readdirSync(dir)) {
    const full = join(dir, name)
    const st = statSync(full)
    if (st.isDirectory()) {
      if (name.startsWith('_')) continue
      walk(full, out)
      continue
    }
    if (!st.isFile()) continue

    if (name === 'page.tsx') {
      out.push(full)
    }
  }
}

function segmentToPath(seg) {
  // [id] -> :id
  const m1 = seg.match(/^\[(.+)\]$/)
  if (m1) {
    const inner = m1[1]
    const mCatch = inner.match(/^\.{3}(.+)$/)
    if (mCatch) return '*'
    return `:${inner}`
  }

  return seg
}

function fileToRoutePath(file) {
  // file: .../src/pages/foo/[id]/page.tsx
  const rel = relative(PAGES_DIR, file)
  const parts = toPosix(rel).split('/')
  // drop trailing page.tsx
  parts.pop()

  const segs = parts.filter(Boolean).map(segmentToPath)
  const path = '/' + segs.join('/')
  return path === '/' ? '/' : path
}

const files = []
walk(PAGES_DIR, files)
files.sort((a, b) => fileToRoutePath(a).localeCompare(fileToRoutePath(b)))

const lines = []
lines.push(`// AUTO-GENERATED by scripts/gen-routes.mjs`)
lines.push(`// Do not edit manually.`)
lines.push('')
lines.push(`import type { RouteDef } from './route'`)
lines.push('')

const entries = []
files.forEach((file, i) => {
  const relFromOut = relative(join(ROOT, 'src'), file)
  const importPath = './' + toPosix(relFromOut).replace(/\.tsx$/, '')
  const alias = `p${i}`
  const path = fileToRoutePath(file)

  lines.push(`import * as ${alias} from ${JSON.stringify(importPath)}`)

  // Require a component export (default or named)
  const componentExpr = `${alias}.default ?? ${alias}.component`

  entries.push(`  {\n    path: ${JSON.stringify(path)},\n    client: (${alias}.client ?? false) as boolean,\n    loader: ${alias}.loader,\n    action: ${alias}.action,\n    component: ${componentExpr} as any,\n  }`)
})

lines.push('')
lines.push(`export const fsRoutes: RouteDef[] = [`)
lines.push(entries.join(',\n'))
lines.push(`]`)
lines.push('')

writeFileSync(OUT_FILE, lines.join('\n'), 'utf8')
console.log(`[gen-routes] wrote ${OUT_FILE} (${files.length} route(s))`)
