// AUTO-GENERATED by scripts/gen-routes.ts
// Do not edit manually.

import type { RouteDef, ApiRouteDef } from './route'
import * as layout0 from "./pages/layout"
import * as p0 from "./pages/about/page"
import * as api0 from "./pages/api/hello/route"

export const fsRoutes: RouteDef<any, any>[] = [
  {
    path: "/about",
    client: ((p0 as any).client ?? false) as boolean,
    metadata: (p0 as any).metadata,
    loader: (p0 as any).loader,
    action: (p0 as any).action,
    component: (props) => (layout0.default as any)({ children: ((p0 as any).default ?? (p0 as any).component)(props) }) as any as any,
  }
]

export const fsApiRoutes: ApiRouteDef[] = [
  {
    path: "/api/hello",
    GET: (api0 as any).GET,
    POST: (api0 as any).POST,
    PUT: (api0 as any).PUT,
    PATCH: (api0 as any).PATCH,
    DELETE: (api0 as any).DELETE,
    HEAD: (api0 as any).HEAD,
    OPTIONS: (api0 as any).OPTIONS,
  }
]
