// AUTO-GENERATED by scripts/gen-routes.ts
// Do not edit manually.

import type { RouteDef, ApiRouteDef } from './route'
import * as layout0 from "./pages/layout"
import * as p0 from "./pages/about/page"
import * as api0 from "./pages/api/hello/route"

export const fsRoutes: RouteDef[] = [
  {
    path: "/about",
    client: (p0.client ?? false) as boolean,
    metadata: p0.metadata,
    loader: p0.loader,
    action: p0.action,
    component: (props) => (layout0.default as any)({ children: (p0.default ?? p0.component)(props) }) as any,
  }
]

export const fsApiRoutes: ApiRouteDef[] = [
  {
    path: "/api/hello",
    GET: (api0 as any).GET,
    POST: (api0 as any).POST,
    PUT: (api0 as any).PUT,
    PATCH: (api0 as any).PATCH,
    DELETE: (api0 as any).DELETE,
    HEAD: (api0 as any).HEAD,
    OPTIONS: (api0 as any).OPTIONS,
  }
]
